// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn5rQAZVc0gfS1IDYSyKPNqc8CbjO4GU8',
    appId: '1:167715141642:web:a02419070c53d7a4c707f3',
    messagingSenderId: '167715141642',
    projectId: 'learning-flutter-8d124',
    authDomain: 'learning-flutter-8d124.firebaseapp.com',
    storageBucket: 'learning-flutter-8d124.appspot.com',
    measurementId: 'G-W6SYS60P68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdU-N02C4wqlFwltMudC3spBBxaR09Gfg',
    appId: '1:167715141642:android:3d94a24f6f3f5e44c707f3',
    messagingSenderId: '167715141642',
    projectId: 'learning-flutter-8d124',
    storageBucket: 'learning-flutter-8d124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YDCyiUd-ig50R2Edj6yUQxZ9-hnr7K8',
    appId: '1:167715141642:ios:4cd33319e02dbfddc707f3',
    messagingSenderId: '167715141642',
    projectId: 'learning-flutter-8d124',
    storageBucket: 'learning-flutter-8d124.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YDCyiUd-ig50R2Edj6yUQxZ9-hnr7K8',
    appId: '1:167715141642:ios:40b9d214eaa8e4f2c707f3',
    messagingSenderId: '167715141642',
    projectId: 'learning-flutter-8d124',
    storageBucket: 'learning-flutter-8d124.appspot.com',
    iosBundleId: 'com.example.learningFlutter.RunnerTests',
  );
}
